apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: voting
  name: voting-user-role
  annotations:
    fluxcd.io/ignore: "false"
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "replicationcontrollers"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
