apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-deploy
    team: dev-team
  name: sample-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-deploy
  template:
    metadata:
      labels:
        app: sample-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
