apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sample-nginx
    team: marketing
  name: sample-nginx
spec:
  containers:
  - env:
    - name: DATA
      value: /var/data
    command: ["/bin/sh", "-c", "touch /tmp/healthy"]
    image: nginx
    name: sample-nginx
    ports:
    - containerPort: 80
