apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sample-web
    team: web-team
  name: sample-init
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: contentdir
      mountPath: /usr/share/nginx/html
    livenessProbe:
      httpGet:
        path: /
        port: 80
  initContainers:
  - name: install
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello There!!' > /work-dir/index.html"]
    volumeMounts:
    - name: contentdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: contentdir
    emptyDir: {}
