apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-config2
spec:
  containers:
    - name: main
      image: busybox
      command: [ "/bin/sh", "-c", "env; sleep 3600" ]
      envFrom:
      - configMapRef:
          name: sample-config

