apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: sample-store
    team: data-team
  name: sample-store
spec:
  containers:
  - command: ["/bin/sh", "-c", "touch /mnt/data/healthy; sleep 60"]
    env:
    - name: DATA
      value: /var/data
    livenessProbe:
      exec:
        command: ["cat", "/mnt/data/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 5
    image: busybox
    name: sample-pod
    volumeMounts:
    - name: pod-storage
      mountPath: /mnt/data
  volumes:
    - name: pod-storage
      emptyDir: {}
