apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-secret3
spec:
  containers:
    - name: main
      image: busybox
      command: [ "/bin/sh", "-c", "ls -l /mnt/secrets; sleep 3600" ]
      volumeMounts:
      - name: secret-vol
        mountPath: /mnt/secrets
  volumes:
    - name: secret-vol
      secret:
        secretName: sample-secret
