apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: sample-store-azurefiles
    team: azure-team
  name: sample-store-azurefiles
spec:
  containers:
  - command: ["/bin/sh", "-c", "touch /mnt/data/healthy; sleep 3600"]
    livenessProbe:
      exec:
        command: ["cat", "/mnt/data/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 5
    image: busybox
    name: sample-pod
    volumeMounts:
    - name: pod-azure-storage
      mountPath: /mnt/data
  volumes:
    - name: pod-azure-storage
      persistentVolumeClaim:
        claimName: sample-pvc
