apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: sample-pod
    team: marketing
  name: sample-pod
spec:
  containers:
  - command: ["/bin/sh", "-c", "touch /tmp/healthy; sleep 3600"]
    env:
    - name: DATA
      value: /var/data
    livenessProbe:
      exec:
        command: ["cat", "/tmp/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 5
    image: busybox
    name: sample-pod
