apiVersion: v1
kind: Pod
metadata:
  name: sample-pod-secret1
spec:
  containers:
    - name: main
      image: busybox
      command: [ "/bin/sh", "-c", "env; sleep 3600" ]
      env:
      - name: FAVORITE_FOOD
        valueFrom:
          secretKeyRef:
            name: sample-secret
            key: favoriteFood

