apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: daveuser-nodereader-global
  annotations:
    fluxcd.io/ignore: "false"
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: "dahoer@microsoft.com" # ME
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
