apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: itgroup-nodereader-global
  annotations:
    fluxcd.io/ignore: "false"
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "d39f2c34-4cb7-4c89-b4b5-c645f7fa708d" # IT Group
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
